### ISSUE TITLE
面试题27_MirrorOfBinaryTree，Test3用例Recursively输出有误。

### ISSUE THREAD

**Issue by yaoya0111** [zhedahht/CodingInterviewChinese2#28]
运行结果：
![wrong_answer.png](https://i.loli.net/2018/11/19/5bf21df7bdf38.png)
linux 4.15.0-36-generic 
gcc 5.4.0

**Comment by lixiang2017** [comment]
![image](https://user-images.githubusercontent.com/25242627/49508612-17b4ce00-f8be-11e8-9a0f-11723bf4fea4.png)
我这边运行结果是对的。
你是不是没在Test3()里调用MirrorRecursively(pNode8);或者把它注释掉了。

**Comment by yaoya0111** [comment]
> ![image](https://user-images.githubusercontent.com/25242627/49508612-17b4ce00-f8be-11e8-9a0f-11723bf4fea4.png)
> 我这边运行结果是对的。
> 你是不是没在Test3()里调用MirrorRecursively(pNode8);或者把它注释掉了。

我的运行结果中第一次Recursively无效，但是第二次结果却调用成功了。
而且我确定我没有改动代码，直接编译的。
