### ISSUE TITLE
面试题14剪绳子问题，为什么绳子的长度不能是小数？

### ISSUE THREAD

**Issue by naget** [zhedahht/CodingInterviewChinese2#31]
书中写到

 >动态规划解法，因为1\*2>1\*1*1所以f(3)=2。

但是题目并没有说绳子长度不可以为小数，所以1.5\*1.5>1\*2，f(3)=1.5\*1.5不是吗？

**Comment by LiuLei95** [comment]
题目上写了，长度为n，绳子剪成m段（m、n都是整数）啊。。。
