### ISSUE TITLE
p98-剪绳子-贪婪算法-代码有误

### ISSUE THREAD

**Issue by luzijing** [zhedahht/CodingInterviewChinese2#6]
f(1)=1,f(2)=1,f(3)=2
所以不用考虑length=4，直接 int timsOf3 = length/3就行了
return (int)(pow(3,timsOf3));

**Comment by zhedahht** [comment]
当绳子的长度为4时，如果剪成长度分别为1、3两段，乘积为3。如果剪成长度分别为2、2两段，乘积为4。所以此时不能按照尽可能剪出长度为3的绳子。
