### ISSUE TITLE
面试题47，解法错误，得出的并不是最大价值

### ISSUE THREAD

**Issue by lhphysics** [zhedahht/CodingInterviewChinese2#68]
棋盘如下时，按照给出的解题思路，沿着带引号的的路线取（1，12，5，7，7，16，5），最大价值为53：
`1`      10       3     8
`12`     2        9     6
`5`      `7`       4     11
 3       `7`     `16`   `5`

但是如果如下棋盘呢，应该是如下路线才是最大价值（1，12，5，7，4，50，5），最大价值为84，却不是按照题目给的解题方法获取的，所以思路有问题，或者题目给的限定条件有问题，麻烦再看一下呢
`1`      10       3     8
`12`     2        9     6
`5`      `7`      `4`   `50`
 3        7       16   `5`

**Comment by zhedahht** [comment]
对于棋盘如下棋盘，最大值应该是85，沿着路线1, 12, 2, 9, 6, 50, 5：
1 10 3 8
12 2 9 6
5 7 4 50
3 7 16 5

书中的参考代码能够算出正确的结果。可以运行下面的代码检验测试结果：
https://ideone.com/ga0pp6
